# This is a basic workflow to help you get started with Actions

name: Dependabot JIRA issue for dependabot PRs
on:
  pull_request:
    branches: [ master ]
    #specify on dependabot PR

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  jira_issue:
      runs-on: ubuntu-latest
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      steps:
        - name: Checks if Dependabot PR
          if: ${{github.event.pull_request.user.login  == 'dependabot[bot]' || github.event.pull_request.user.login  == 'app/dependabot' || github.event.pull_request.user.login  == 'app/dependabot-preview' || github.event.pull_request.user.login == 'daniellaskinner'}}
          run: echo "This is a dependabot PR"
#            instead of echo, open a JIRA issue

        - name: Login to JIRA
          if: ${{github.event.pull_request.user.login  == 'dependabot[bot]' || github.event.pull_request.user.login  == 'app/dependabot' || github.event.pull_request.user.login  == 'app/dependabot-preview' || github.event.pull_request.user.login == 'daniellaskinner'}}
          uses: atlassian/gajira-login@master
          env:
              JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
              JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
              JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

        - name: Jira Issue creation
          id: create
          if: ${{github.event.pull_request.user.login  == 'dependabot[bot]' || github.event.pull_request.user.login  == 'app/dependabot' || github.event.pull_request.user.login  == 'app/dependabot-preview' || github.event.pull_request.user.login == 'daniellaskinner'}}
          uses: atlassian/gajira-create@master
          with:
            project: GAJL
            issuetype: Task
            summary: |
              Build completed for ${{ github.repository }}
            description: Created automatically via GitHub Actions
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Log created JIRA issue
          run: echo "Issue ${{ steps.create.outputs.issue }} was created"


#        - uses: actions/checkout@v2
#          if: ${{github.event.pull_request.user.login  == 'dependabot[bot]' || github.event.pull_request.user.login  == 'app/dependabot' || github.event.pull_request.user.login  == 'app/dependabot-preview'}}
#
#        - name: Open JIRA issue if Dependabot PR
#          if: ${{github.event.pull_request.user.login  == 'dependabot[bot]' || github.event.pull_request.user.login  == 'app/dependabot' || github.event.pull_request.user.login  == 'app/dependabot-preview'}}
#          env:
#            pr_title: ${{github.event.pull_request.title}}
#            pr_number: ${{github.event.pull_request.number}}
#            pr_url: ${{github.event.pull_request.url}}
#          run: echo "Hello world"
#           main: 'githubAction.js'
            # Insert the call to the JIRA issue creator thingy
#            title="Dependabot PR $pr_title opened"
#            body="Dependabot has opened PR #$pr_number
#                   Link: $pr_url"
