# This is a basic workflow to help you get started with Actions

name: Dependabot JIRA issue for dependabot PRs
on:
  pull_request:
    branches: [ master ]
    #specify on dependabot PR

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  jira_issue:
      runs-on: ubuntu-latest
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      steps:
        - name: Check if pull request is dependabot
          if: ${{ github.event.pull_request.user.login == 'daniellaskinner' }}
          run: exit 1

        - name: Login to JIRA
          if: ${{github.event.pull_request.user.login  == 'dependabot[bot]' || github.event.pull_request.user.login  == 'app/dependabot' || github.event.pull_request.user.login  == 'app/dependabot-preview' || github.event.pull_request.user.login == 'daniellaskinner'}}
          uses: atlassian/gajira-login@master
          env:
              JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
              JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
              JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

        - name: Jira Issue creation
          id: create
          if: ${{github.event.pull_request.user.login  == 'dependabot[bot]' || github.event.pull_request.user.login  == 'app/dependabot' || github.event.pull_request.user.login  == 'app/dependabot-preview' || github.event.pull_request.user.login == 'daniellaskinner'}}
          uses: atlassian/gajira-create@master
          with:
            project: GAJL
            issuetype: Task
            summary: |
              HELLO THIS IS A TEST Build completed for ${{ github.event.pull_request.title }}
#              this will be dependabot stuff e.g. github.event.pull_request.name ?
            description: ${{ github.event.pull_request.body }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Log created JIRA issue
          run: echo "Issue ${{ steps.create.outputs.issue }} was created"
